// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'GOOGLE_API_KEY',
    appId: '1:904823643813:web:67e1bb0d1940a22a1b374c',
    messagingSenderId: '904823643813',
    projectId: 'zporternotes',
    authDomain: 'zporternotes.firebaseapp.com',
    storageBucket: 'zporternotes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'GOOGLE_API_KEY',
    appId: '1:904823643813:android:223d1221af2793a51b374c',
    messagingSenderId: '904823643813',
    projectId: 'zporternotes',
    storageBucket: 'zporternotes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'GOOGLE_API_KEY',
    appId: '1:904823643813:ios:e85738bb9f9d5bd41b374c',
    messagingSenderId: '904823643813',
    projectId: 'zporternotes',
    storageBucket: 'zporternotes.firebasestorage.app',
    iosBundleId: 'com.example.zporterNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'GOOGLE_API_KEY',
    appId: '1:904823643813:ios:e85738bb9f9d5bd41b374c',
    messagingSenderId: '904823643813',
    projectId: 'zporternotes',
    storageBucket: 'zporternotes.firebasestorage.app',
    iosBundleId: 'com.example.zporterNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'GOOGLE_API_KEY',
    appId: '1:904823643813:web:baabdb7ad1a494d21b374c',
    messagingSenderId: '904823643813',
    projectId: 'zporternotes',
    authDomain: 'zporternotes.firebaseapp.com',
    storageBucket: 'zporternotes.firebasestorage.app',
  );
}
